package edu.gcu.cst105.week3.uno;

public class Player {

	public static void main(String[] args) {
		Player player1 = new Player();
		player1.buildDeck();

	}
	
	private void buildDeck() {
		Card [] card = {
				new Card("Blue", "0"),
				new Card("Blue", "1"),
				new Card("Blue", "1"),
				new Card("Blue", "2"),
				new Card("Blue", "2"),
				new Card("Blue", "3"),
				new Card("Blue", "3"),
				new Card("Blue", "4"),
				new Card("Blue", "4"),
				new Card("Blue", "5"),
				new Card("Blue", "5"),
				new Card("Blue", "6"),
				new Card("Blue", "6"),
				new Card("Blue", "7"),
				new Card("Blue", "7"),
				new Card("Blue", "8"),
				new Card("Blue", "8"),
				new Card("Blue", "9"),
				new Card("Blue", "9"),
				new Card("Blue", "Skip"),
				new Card("Blue", "Skip"),
				new Card("Blue", "Reverse"),
				new Card("Blue", "Reverse"),
				new Card("Blue", "Draw Two"),
				new Card("Blue", "Draw Two"),				
				new Card("Red", "0"),
				new Card("Red", "1"),
				new Card("Red", "1"),
				new Card("Red", "2"),
				new Card("Red", "2"),
				new Card("Red", "3"),
				new Card("Red", "3"),
				new Card("Red", "4"),
				new Card("Red", "4"),
				new Card("Red", "5"),
				new Card("Red", "5"),
				new Card("Red", "6"),
				new Card("Red", "6"),
				new Card("Red", "7"),
				new Card("Red", "7"),
				new Card("Red", "8"),
				new Card("Red", "8"),
				new Card("Red", "9"),
				new Card("Red", "9"),				
				new Card("Red", "Skip"),
				new Card("Red", "Skip"),
				new Card("Red", "Reverse"),
				new Card("Red", "Reverse"),				
				new Card("Red", "Draw Two"),
				new Card("Red", "Draw Two"),				
				new Card("Yellow", "0"),
				new Card("Yellow", "1"),
				new Card("Yellow", "1"),
				new Card("Yellow", "2"),
				new Card("Yellow", "2"),
				new Card("Yellow", "3"),
				new Card("Yellow", "3"),
				new Card("Yellow", "4"),
				new Card("Yellow", "4"),
				new Card("Yellow", "5"),
				new Card("Yellow", "5"),
				new Card("Yellow", "6"),
				new Card("Yellow", "6"),
				new Card("Yellow", "7"),
				new Card("Yellow", "7"),
				new Card("Yellow", "8"),
				new Card("Yellow", "8"),
				new Card("Yellow", "9"),
				new Card("Yellow", "9"),
				new Card("Yellow", "Skip"),
				new Card("Yellow", "Skip"),
				new Card("Yellow", "Reverse"),
				new Card("Yellow", "Reverse"),
				new Card("Yellow", "Draw Two"),
				new Card("Yellow", "Draw Two"),				
				new Card("Green", "0"),
				new Card("Green", "1"),
				new Card("Green", "1"),
				new Card("Green", "2"),
				new Card("Green", "2"),
				new Card("Green", "3"),
				new Card("Green", "3"),
				new Card("Green", "4"),
				new Card("Green", "4"),
				new Card("Green", "5"),
				new Card("Green", "5"),
				new Card("Green", "6"),
				new Card("Green", "6"),
				new Card("Green", "7"),
				new Card("Green", "7"),
				new Card("Green", "8"),
				new Card("Green", "8"),
				new Card("Green", "9"),
				new Card("Green", "9"),
				new Card("Green", "Skip"),
				new Card("Green", "Skip"),
				new Card("Green", "Reverse"),
				new Card("Green", "Reverse"),
				new Card("Green", "Draw Two"),
				new Card("Green", "Draw Two"),				
				new Card("Black", "Wild"),
				new Card("Black", "Wild"),
				new Card("Black", "Wild"),
				new Card("Black", "Wild"),
				new Card("Black", "Draw Four Wild"),
				new Card("Black", "Draw Four Wild"),
				new Card("Black", "Draw Four Wild"),
				new Card("Black", "Draw Four Wild")
		};
		
		Deck uno = new Deck(card);
		uno.shuffle();
		for (int numCard = 0; numCard < 7; numCard++) {
			System.out.println(uno.deal().toString());
		}		
	}

}
